---
title: "Exam-02"
author: "Pablo Vivas"
date: "`r Sys.Date()`"
format:
  html:
    toc: true
    toc-location: right
    toc-depth: 1
    code-copy: true
    code-fold: true
    highlight-style: nord
  docx:
    toc: true
    toc-depth: 3
    fig-align: center
    df-print: tibble
    highlight-style: nord
    output-file: exam-02-pablo-vivas.docx
execute:
  warning: false
  error: false
  echo: true
theme: simplex
---

```{r}
#| label: set-up
#| echo: false

library(gt)
library(lavaan)
library(stringr)
library(tidyverse)
```

# Question 1

```{r}
#| label: read data

data = read_csv("./data/personality-1.csv")

data_sub = data |> 
  select(str_c("pers", c("03", "07", 11, 13, 16, 26, 36)))
```


## a)

## b)

```{r}
#| label: fit one factor cfa 
mod_01 = '
  f1 =~ pers03 + pers07 + pers11 + pers13 + pers16 + pers26 + pers36
'

cfa_01 = cfa(mod_01, data = data_sub)
```

## c)

## d)

## e)

# Question 2

```{r}
#| label: fit efa all data

efa_01 = efa()
```

## a)

## b)

## c)

## d)

## e)

## f)

# Question 3

## a)

## b)